openapi: 3.0.1
info:
  title: Describe.me
  description: Опиши функцию - спаси дерево!
  contact:
    email: pavlov.nick.2000@gmail.com
  license:
    name: Beerware License (Я люблю бланши, Шляпос любит тёмное)
    url: https://spdx.org/licenses/Beerware.html
  version: 1.0.0
servers:
- url: http://describe-me.ru/api

tags:
- name: User
  description: Данные о пользовательском профиле

- name: Language
  description: Языки программирования, на которых написаны функции в постах

- name: Preference
  description: Языки, которые предпочитает пользователь

- name: Post
  description: Посты, содержащие код функции для описания

- name: Package
  description: Наборы постов, собранные по общему признаку
  
- name: Description
  description: Описания, даваемые постам пользователями
  
- name: Rating
  description: Оценки, которые пользователи дали описаниям
  

paths:
  /user/register:
    post:
      tags:
      - User
      summary: Создать аккаунт
      operationId: registerUser
  /user/login:
    get:
      tags:
      - User
      summary: Войти в аккаунт
      operationId: loginUser
  /user/logout:
    get:
      tags:
      - User
      summary: Выйти из аккаунта
      operationId: logoutUser
  /user/{login}:
    get:
      tags:
      - User
      summary: Получения профиля пользователя
      operationId: getUser
    put:
      tags:
      - User
      summary: Обновить данные пользователя
      operationId: updateUser
  /lang/list:
    get:
      tags:
      - Language
      summary: Получить список всех языков
      operationId: listLanguages
      security:
      - describeMeAuth:
        - student
        - teacher
        
  /pref:
    post:
      tags: 
      - Preference
      summary: Добавить языковое предпочтение
      operationId: createPreference
      security:
        - describeMeAuth:
          - student
          - teacher
        
    delete:
      tags: 
      - Preference
      summary: Удалить языковое предпочтение
      operationId: deletePreference
      security:
        - describeMeAuth:
          - student
          - teacher
  
  /pref/list/{login}:
    get:
      tags:
      - Preference
      summary: Получить все языковые предпочтения пользователя
      operationId: listPreferences
      security:
      - describeMeAuth:
        - student
        - teacher
  
  
  /post:
    post:
      tags:
      - Post
      summary: Создать карточку
      operationId: createPost
      security:
        - describeMeAuth:
          - teacher
          
  /post/{postID}:
    get:
      tags:
      - Post
      summary: Получить карточку
      operationId: getPost
      security:
        - describeMeAuth:
          - student
          - teacher
      
  /post/desc/{postID}:
    get:
      tags:
      - Post
      summary: Получить описания к карточке
      operationId: getPostDescriptions
      security:
        - describeMeAuth:
          - student
          - teacher
      
    patch:
      tags:
      - Post
      summary: Обновить карточку
      operationId: updatePost
      security:
        - describeMeAuth:
          - teacher
  
  /post/desc/rand/{postID}:
    get:
      tags:
      - Post
      summary: Получить случайное описание к карточке
      operationId: getRandomPostDescription
      security:
        - describeMeAuth:
          - student
          - teacher
  
  /pack:
    post:
      tags:
      - Package
      summary: Создать набор карточек
      operationId: createPackage
      security:
        - describeMeAuth:
          - teacher
          
  /pack/append/{postID}:
    patch:
      tags:
      - Package
      summary: Добавить к набору карточек новую карточку
      operationId: appendToPackage
      security:
        - describeMeAuth:
          - teacher
    
  /pack/remove/{postID}:
    patch:
      tags:
      - Package
      summary: Убрать карточку из набора карточек
      operationId: removeFromPackage
      security:
        - describeMeAuth:
          - teacher
    
  /pack/list/{login}:
    get:
      tags:
      - Package
      summary: Получить список наборов карточек, видимых пользователю
      operationId: listPackages
      security:
        - describeMeAuth:
          - student
          - teacher
    
  /pack/list/{name}:
    get:
      tags:
      - Package
      summary: Получить все карточки из набора
      operationId: getPostsFromPackage
      security:
        - describeMeAuth:
          - student
          - teacher
  
  /desc:
    post:
      tags:
      - Description
      summary: Создать описание к карточке
      operationId: createDescription
      security:
        - describeMeAuth:
          - student
          - teacher
          
    
  /desc/{descriptionID}:
    get:
      tags:
      - Description
      summary: Получить описание по ID
      operationId: getDescription
      security:
        - describeMeAuth:
          - student
          - teacher
  
  /rate/like/{descriptionID}:
    post:
      tags:
      - Rating
      summary: Поставить описанию лайк
      operationId: likeDescription
      security:
        - describeMeAuth:
          - student
          - teacher
          
  /rate/dislike/{descriptionID}:
    post:
      tags:
      - Rating
      summary: Поставить описанию дизлайк
      operationId: dislikeDescription
      security:
        - describeMeAuth:
          - student
          - teacher
          
  /rate/purge/{descriptionID}:
    post:
      tags:
      - Rating
      summary: Убрать реакцию с описания
      operationId: purgeDescription
      security:
        - describeMeAuth:
          - student
          - teacher
          
  /rate/rating/{descriptionID}:
    get:
      tags:
      - Rating
      summary: Получить рейтинг описания
      operationId: getDescriptionRating
      security:
        - describeMeAuth:
          - student
          - teacher
  
components:
  securitySchemes:
    describeMeAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            student: Доступ для студентов
            teacher: Доступ для преподавателей